export const FETCH_ROCKETS_REQUEST = "FETCH_ROCKETS_REQUEST";

export const FETCH_DRAGONS_REQUEST = "FETCH_DRAGONS_REQUEST";

export const FETCH_ROCKETS_SUCCESS = "FETCH_ROCKETS_SUCCESS";

export const FETCH_DRAGONS_SUCCESS = "FETCH_DRAGONS_SUCCESS";

export const FETCH_SPACECRAFTS_FAIL = "FETCH_SPACECRAFTS_FAIL";

export const FETCH_ROCKET_DETAILS_REQUEST = "FETCH_ROCKET_DETAILS_REQUEST";

export const FETCH_DRAGON_DETAILS_REQUEST = "FETCH_DRAGON_DETAILS_REQUEST";

export const FETCH_ROCKET_DETAILS_SUCCESS = "FETCH_ROCKET_DETAILS_SUCCESS";

export const FETCH_DRAGON_DETAILS_SUCCESS = "FETCH_DRAGON_DETAILS_SUCCESS";

export const FETCH_SPACECRAFT_DETAILS_FAIL = "FETCH_SPACECRAFT_DETAILS_FAIL";
